pipeline {
  agent { label 'docker' }

  environment {
    IMAGE_NAME = "imaisalama/jenkins-app"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    APP_DIR    = '5-ArgoCD/Lab_25/Jenkins_App'
    K8S_DIR = '5-ArgoCD/Lab_25/k8s'
    GIT_USER = 'MaiSalama'
    GIT_EMAIL = 'imaisalama@gmail.com'
  }

  stages {

    stage('Run Unit Tests') {
      steps {
        dir(APP_DIR) {
          sh 'mvn test'
        }
      }
    }

    stage('Build Application') {
      steps {
        dir(APP_DIR) {
          sh 'mvn package -DskipTests'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir(APP_DIR) {
          sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
        }
      }
    }

    stage('Push Image to Docker Hub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'DockerHub_Credentials',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
          '''
        }
      }
    }

    stage('Delete Local Docker Image') {
      steps {
        sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
      }
    }

    stage('Update Deployment YAML') {
      steps {
        dir(APP_DIR) {
          sh """
            sed -i 's|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g' ../k8s/deployment.yaml

            echo "Updated deployment.yaml:"
            grep image ../k8s/deployment.yaml
          """
        }
      }
    }

    stage('Commit & Push Manifests') {
      steps {
        dir(APP_DIR) {
          withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN')]) 
        {
        sh """
          git config user.name "MaiSalama"
          git config user.email "maisalama@gmail.com"

          git add k8s/deployment.yaml
          git commit -m "chore: update image to ${IMAGE_TAG}" || echo "No changes to commit"

          git push https://${GIT_USER}:${GIT_TOKEN}@github.com/MaiSalama/ivolve_training.git HEAD:main
        """
        }
      }
    }
}

  } // end stages

  post {
    always {
      echo 'Pipeline execution finished'
    }
    success {
      echo 'Application deployed successfully'
    }
    failure {
      echo 'Pipeline failed check logs'
    }
  }

} // end pipeline
