pipeline {
  agent { label 'docker' }

  environment {
    IMAGE_NAME = "imaisalama/jenkins-app"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    APP_DIR    = '4-CICD/Lab_22/Jenkins_App-main'
  }

  stages {

    stage('Run Unit Tests') {
      steps {
        dir(APP_DIR) {
          sh 'mvn test'
        }
      }
    }

    stage('Build Application') {
      steps {
        dir(APP_DIR) {
          sh 'mvn package -DskipTests'
        }
      }
    }


    stage('Build Docker Image') {
      steps {
        dir(APP_DIR) {
          sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
        }
      }
    }

    stage('Push Image to Docker Hub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'DockerHub_Credentials',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
          '''
        }
      }
    }

    stage('Delete Local Docker Image') {
      steps {
        sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
      }
    }

    stage('Update Deployment YAML') {
        steps {
            dir(APP_DIR) {
            sh """
            sed -i 's|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g' deployment.yaml
            """
             }
        }
}

    stage('Deploy to Kubernetes') {
  steps {
    dir(APP_DIR) {
      sh '''
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/jenkins-app
      '''
    }
  }
}

  post {
    always {
      echo 'Pipeline execution finished'
    }
    success {
      echo 'Application deployed successfully'
    }
    failure {
      echo 'Pipeline failed – check logs'
    }
  }
}
